Fixes creation of RPM with updated sources

diff --git a/init/rasmgr.init.in b/init/rasmgr.init.in
--- a/init/rasmgr.init.in
+++ b/init/rasmgr.init.in
@@ -5,14 +5,14 @@
 # chkconfig: - 64 36
 # description: Starts and stops the Rasdaman.
 # processname: rasmgr
-# config: /etc/rasmgr.conf
+# config: /etc/rasdaman/rasmgr.conf
 # config: /etc/sysconfig/rasmgr
 # pidfile: /var/run/rasmgr.pid
 #
 ### BEGIN INIT INFO
 # Provides: rasmgr
-# Required-Start: $local_fs $remote_fs $network $named $postgresql
-# Required-Stop: $local_fs $remote_fs $network
+# Required-Start: $postgresql
+# Required-Stop:
 # Should-Start: distcache
 # Short-Description: Starts and stops the Rasdaman.
 # Description: The Rasdaman Server is a raster data manager.
@@ -43,9 +43,10 @@ wait_for_children=${WAIT_FOR_CHILDREN-5}
 servers=${RASSERVERS-"-all"}
 raslogin=${RASADMIN-rasadmin:d293a15562d3e70b6fdc5ee452eaed40}
 rasdir=${RASDIR-/var/lib/rasdaman}
+raslogdir=${RASLOGDIR-/var/log/rasdaman}
 rasshell=${RASSHELL-/bin/bash}
 petapath=${PETASCOPE_PATH-/usr/share/rasdaman/petascope}
-SETTINGS=${PETASCOPE_SETTINGS-/etc/petascope.conf}
+SETTINGS=${PETASCOPE_SETTINGS-/var/lib/tomcat6/webapps/petascope/WEB-INF/classes/settings.properties}
 
 # To check if postgres cluster was initialised
 # we need this and 
@@ -64,7 +65,6 @@ else
 fi
 
 raslog=$rasdir/startup.log
-raslogdir=/var/log/rasdaman
 rascontrol="RASLOGIN=$raslogin $rasctrl"
 deffile=$rasdir/basictypes.dl
 
@@ -73,7 +73,7 @@ deffile=$rasdir/basictypes.dl
 # when not running is also a failure.  So we just do it the way init scripts
 # are expected to behave here.
 start() {
-	chown -R rasdaman:rasdaman "$raslog" "$raslogdir"
+	chown -R rasdaman:rasdaman "$raslogdir"
 	# Make sure startup-time log file is valid
 	if [ ! -e "$raslog" -a ! -h "$raslog" ]
 	then
@@ -102,7 +102,8 @@ start() {
 
         echo -n $"Starting $prog: "
 	$SU -l rasdaman -s "$rasshell" -c "$rasmgr &" >> "$raslog" 2>&1 < /dev/null
-	if [[ $? != 0 ]]
+	RETVAL=$?
+	if [[ $RETVAL = 0 ]]
 	then
 	        echo
         	touch ${lockfile}
@@ -113,7 +114,7 @@ start() {
 
 	for SRV in $servers
 	do
-		echo -n $"$rascontrol: starting server $SRV..."
+		echo $"$rasctrl: starting server $SRV..."
 		$SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x up srv $SRV" >> "$raslog" 2>&1 < /dev/null
 		RETVAL=$?
 		if [[ $RETVAL != 0 ]]
@@ -129,11 +130,10 @@ start() {
 # httpd parent; this gives enough time for the httpd parent to SIGKILL any
 # errant children.
 stop() {
-	chown -R rasdaman:rasdaman "$raslog" "$raslogdir"
-	running=`$SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x list srv | awk '{ print $2;}'"`
+	running=`$SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x list srv | awk '{ if (\\$6 == \"UP\") print \\$2;}'"`
 	for SRV in $running
 	do
-		echo -n $"$rascontrol: stoping server $SRV..."
+		echo $"$rasctrl: stoping server $SRV..."
 		$SU -l rasdaman -s "$rasshell" -c "$rascontrol -e -q -x down srv $SRV -kill" >> "$raslog" 2>&1 < /dev/null
 	done
 
@@ -147,18 +147,36 @@ stop() {
 }
 
 initdb(){
-	chown -R rasdaman:rasdaman "$raslog" "$raslogdir"
 	bhostname=`hostname`
-	mv /etc/rasmgr.conf /etc/rasmgr.conf.init
-	cat /etc/rasmgr.conf.init | sed -e "s/localhost/$bhostname/g" > /etc/rasmgr.conf
+	mv /etc/rasdaman/rasmgr.conf /etc/rasdaman/rasmgr.conf.init
+	cat /etc/rasdaman/rasmgr.conf.init | sed -e "s/localhost/$bhostname/g" > /etc/rasdaman/rasmgr.conf
 	service postgresql initdb
 	service postgresql start
+	$SU -l postgres -c "createuser -d -r -S rasdaman"
+	RETVAL=$?
+	if [[ $RETVAL != 0 ]]
+	then
+		echo $"createuser failed"
+		exit $!
+	fi
+	$SU -l rasdaman -s "$rasshell" -c "createdb RASBASE"
+	RETVAL=$?
+	if [[ $RETVAL != 0 ]]
+	then
+		echo $"createdb failed"
+		exit $!
+	fi
+	$SU -l rasdaman -s "$rasshell" -c "$rasdl -c --connect RASBASE && $rasdl -r $deffile -i --connect RASBASE"
+	RETVAL=$?
+	if [[ $RETVAL != 0 ]]
+	then
+		echo $"rasdl failed"
+		exit $!
+	fi
+}
 
-	$SU -l postgres -c "createuser -d -r -S rasdaman" || exit $!
-	$SU -l rasdaman -s "$rasshell" -c "createdb RASBASE" || exit $!
-	$SU -l rasdaman -s "$rasshell" -c "$rasdl -c --connect RASBASE && $rasdl -r $deffile -i --connect RASBASE" || exit $!
-	
-	# petascope
+initpetascopedb(){
+
         $SU -l rasdaman -s "$rasshell" -c "createdb petascopedb" || exit $!
 	
 	DB=`grep metadata_url "$SETTINGS" | awk -F "/" '{print $4}' | tr -d '\n'`
@@ -177,9 +195,6 @@ initdb(){
 		$SU -l rasdaman -s "$rasshell" -c "$PSQL -c 'drop table ps_tmp' > /dev/null"
 		echo OK
 	fi
-
-	# start rasdaman
-	start
 
 	# rasdaman connection details
 	RAS_USER=`grep rasdaman_admin_user "$SETTINGS" | awk -F "=" '{print $2}' | tr -d '\n'`
@@ -201,7 +216,7 @@ initdb(){
 		echo Sample coverage data NIR already inserted
 	else
 	        echo Inserting coverage NIR into rasdaman
-		$SU -l rasdaman -s "$rasshell" -c "$RASQL -q 'insert into NIR values inv_tiff($1)' --file $petapath/nir.tiff > /dev/null 2>&1"
+		$SU -l rasdaman -s "$rasshell" -c "$RASQL -q 'insert into NIR values inv_tiff(\$1)' --file $petapath/nir.tiff > /dev/null 2>&1"
 	fi
 
 	$SU -l rasdaman -s "$rasshell" -c "$RASQL -q 'create collection mean_summer_airtemp GreySet' > /dev/null 2>&1"
@@ -209,12 +224,12 @@ initdb(){
 		echo Sample coverage data mean_summer_airtemp already inserted
 	else
         	echo Inserting coverage mean_summer_airtemp into rasdaman
-		$SU -l rasdaman -s "$rasshell" -c "$RASQL -q 'insert into mean_summer_airtemp values inv_tiff($1)' --file $petapath/mean_summer_airtemp.tif > /dev/null 2>&1"
+		$SU -l rasdaman -s "$rasshell" -c "$RASQL -q 'insert into mean_summer_airtemp values inv_tiff(\$1)' --file $petapath/mean_summer_airtemp.tif > /dev/null 2>&1"
 	fi
 	
 	# update petascope db
 	counter=0
-	while [ -e update$counter.sql ]; do
+	while [ -e $petapath/update$counter.sql ]; do
 		$SU -l rasdaman -s "$rasshell" -c "$PSQL < $petapath/update$counter.sql > /dev/null 2>&1"
 		let counter="$counter"+1
 	done
@@ -222,11 +237,30 @@ initdb(){
 }
 
 dropdb(){
-	echo dropping databases...
+	echo dropping rasbase...
 	$SU -l rasdaman -s "$rasshell" -c "dropdb RASBASE"
-	$SU -l rasdaman -s "$rasshell" -c "dropdb petascopedb"
+	RETVAL=$?
+	if [[ $RETVAL != 0 ]]
+	then
+		echo $"dropdb failed"
+	fi
 	echo dropping user...
 	$SU -l postgres -c "dropuser rasdaman"
+	RETVAL=$?
+	if [[ $RETVAL != 0 ]]
+	then
+		echo $"drop user failed"
+	fi
+}
+
+droppetascopedb(){
+	echo dropping petascopedb...
+	$SU -l rasdaman -s "$rasshell" -c "dropdb petascopedb"
+	RETVAL=$?
+	if [[ $RETVAL != 0 ]]
+	then
+		echo $"dropdb failed"
+	fi
 }
 
 # See how we were called.
@@ -255,14 +289,19 @@ case "$1" in
   initdb)
 	initdb
 	;;
+  initpetascopedb)
+	initpetascopedb
+	;;
   dropdb)
 	dropdb
 	;;
+  droppetascopedb)
+	droppetascopedb
+	;;
   *)
-	echo $"Usage: $prog {start|stop|restart|condrestart|status|initdb}"
+	echo $"Usage: $prog {start|stop|restart|condrestart|status|initdb|dropdb|initpetascopedb|droppetascopedb}"
 	RETVAL=3
 esac
 
 exit $RETVAL
-
 
